import bcrypt from "bcryptjs";
import { db } from "@workspace/db";
import { deviationsTable, capaTable, changeControlTable, usersTable, auditLogsTable, attachmentsTable, efficacyReviewsTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data (order respects FK constraints)
  await db.delete(efficacyReviewsTable);
  await db.delete(attachmentsTable);
  await db.delete(auditLogsTable);
  await db.delete(capaTable);
  await db.delete(deviationsTable);
  await db.delete(changeControlTable);
  await db.delete(usersTable);

  // Hash passwords
  const adminHash = await bcrypt.hash("admin123", 10);
  const userHash = await bcrypt.hash("user123", 10);

  // Users
  const [u1, u2, u3, u4] = await db.insert(usersTable).values([
    { name: "Dr. Sarah Chen", email: "sarah.chen@capalyst.com", roles: ["QA", "Admin"], passwordHash: adminHash },
    { name: "James Holloway", email: "james.holloway@capalyst.com", roles: ["QA"], passwordHash: adminHash },
    { name: "Ana Martinez", email: "ana.martinez@capalyst.com", roles: ["User"], passwordHash: userHash },
    { name: "Michael Delaney", email: "michael.delaney@capalyst.com", roles: ["QA", "User"], passwordHash: adminHash },
    { name: "Priya Nair", email: "priya.nair@capalyst.com", roles: ["User"], passwordHash: userHash },
    { name: "Thomas Birch", email: "thomas.birch@capalyst.com", roles: ["User"], passwordHash: userHash },
  ]).returning();

  // Deviations
  const deviations = await db.insert(deviationsTable).values([
    {
      deviationNumber: "DEV-0001",
      title: "Temperature excursion in cold storage unit C-04",
      description: "Cold storage unit C-04 recorded temperatures above 8°C for approximately 4 hours due to a compressor fault. Affected batches: BT-2024-0451 through BT-2024-0460.",
      deviationType: "Equipment",
      status: "In Progress",
      eventDate: "2026-06-01",
      detectionDate: "2026-06-01",
      dueDate: "2026-07-01",
      areaResponsible: "Cold Chain Management",
      qaExpert: "Dr. Sarah Chen",
      rootCause: "Compressor failure due to inadequate preventive maintenance schedule.",
      investigation: "Root cause identified as failure in PM schedule adherence. Engineering review initiated.",
    },
    {
      deviationNumber: "DEV-0002",
      title: "Out-of-specification dissolution result for batch BT-2026-0089",
      description: "Batch BT-2026-0089 (Metformin 500mg tablets) failed dissolution test on Stage 2 testing with 68% at Q=75%.",
      deviationType: "Process",
      status: "Open",
      eventDate: "2026-06-05",
      detectionDate: "2026-06-05",
      dueDate: "2026-07-05",
      areaResponsible: "Manufacturing - Solid Dosage",
      qaExpert: "James Holloway",
      rootCause: null,
      investigation: "Stage 2 testing confirms OOS. Laboratory investigation initiated per SOP-LAB-012.",
    },
    {
      deviationNumber: "DEV-0003",
      title: "Label mix-up identified during packaging audit",
      description: "During a routine packaging audit, 200 units of Product A were found with Product B labels applied. Product A and B are different strengths of the same API.",
      deviationType: "Documentation",
      status: "Closed",
      eventDate: "2026-05-15",
      detectionDate: "2026-05-16",
      dueDate: "2026-06-15",
      areaResponsible: "Packaging Operations",
      qaExpert: "Dr. Sarah Chen",
      rootCause: "Artwork management SOP was not followed; incorrect label artwork file used during setup.",
      investigation: "All 200 affected units quarantined and destroyed. Artwork management process reviewed and updated.",
    },
    {
      deviationNumber: "DEV-0004",
      title: "Environmental monitoring alert — viable particle count exceedance",
      description: "Grade B cleanroom monitoring detected viable counts above alert limit (>5 CFU/m³) in Zone 3 on three consecutive monitoring events.",
      deviationType: "Environmental",
      status: "In Progress",
      eventDate: "2026-05-28",
      detectionDate: "2026-05-28",
      dueDate: "2026-06-10",
      extendedDate: "2026-06-28",
      areaResponsible: "Aseptic Fill",
      qaExpert: "Ana Martinez",
      rootCause: "HVAC filter replacement was overdue by 6 weeks.",
      investigation: "HVAC filters replaced. Interim enhanced monitoring implemented. Batch impact assessment ongoing.",
    },
    {
      deviationNumber: "DEV-0005",
      title: "Equipment calibration overdue — pH meter LAB-0047",
      description: "pH meter LAB-0047 used in buffer preparation was found to be 45 days past its calibration due date. All buffers prepared in this period require impact assessment.",
      deviationType: "Equipment",
      status: "Overdue",
      eventDate: "2026-06-10",
      detectionDate: "2026-06-10",
      dueDate: "2026-06-15",
      areaResponsible: "QC Laboratory",
      qaExpert: "Michael Delaney",
      rootCause: null,
      investigation: "Calibration tracking system gap identified. Equipment recalled for immediate calibration.",
    },
    {
      deviationNumber: "DEV-0006",
      title: "Raw material specification failure — Excipient Lot RM-2026-0221",
      description: "Microcrystalline cellulose lot RM-2026-0221 failed particle size distribution test (D90 = 142µm vs. limit ≤120µm).",
      deviationType: "Material",
      status: "Closed",
      eventDate: "2026-04-20",
      detectionDate: "2026-04-20",
      dueDate: "2026-05-20",
      areaResponsible: "Warehouse / Receiving",
      qaExpert: "James Holloway",
      rootCause: "Supplier process deviation. Supplier has been notified and a SCAR has been raised.",
      investigation: "Affected lot rejected and returned to supplier. Alternative approved lot used. SCAR sent to supplier.",
    },
    {
      deviationNumber: "DEV-0007",
      title: "SOP non-compliance — critical process parameter not recorded",
      description: "Batch record review for batch BT-2026-0102 revealed that granulation endpoint determination was not recorded per SOP-MFG-034.",
      deviationType: "Documentation",
      status: "Open",
      eventDate: "2026-06-12",
      detectionDate: "2026-06-14",
      dueDate: "2026-07-14",
      areaResponsible: "Manufacturing",
      qaExpert: "Priya Nair",
      rootCause: null,
      investigation: "Operator interviewed. Batch record reviewed with QA. Training assessment to be conducted.",
    },
    {
      deviationNumber: "DEV-0008",
      title: "Retained sample storage condition deviation",
      description: "Retained samples for three batches (BT-2025-0412, BT-2025-0415, BT-2025-0419) were stored at 30°C instead of required 25°C ± 2°C for a period of 3 months.",
      deviationType: "Storage",
      status: "Closed",
      eventDate: "2026-03-10",
      detectionDate: "2026-03-10",
      dueDate: "2026-04-10",
      areaResponsible: "Stability Laboratory",
      qaExpert: "Dr. Sarah Chen",
      rootCause: "Thermostat sensor failure not detected during routine monitoring due to a data logger software bug.",
      investigation: "Accelerated stability testing initiated for affected samples. Data logger software patched.",
    },
  ]).returning();

  // CAPAs
  const capas = await db.insert(capaTable).values([
    {
      capaNumber: "CAPA-0001",
      deviationId: deviations[0].id,
      title: "Revise preventive maintenance schedule for cold storage units",
      description: "Update PM schedule to include monthly compressor health checks. Install redundant temperature alarms with SMS notifications to on-call personnel.",
      capaType: "Corrective",
      status: "In Progress",
      creationDate: "2026-06-03",
      initialPlannedDate: "2026-07-03",
      implementationLeader: "James Holloway",
      location: "Cold Chain / Engineering",
      externalReferences: "ENG-PM-2026-0041",
    },
    {
      capaNumber: "CAPA-0002",
      deviationId: deviations[2].id,
      title: "Implement electronic artwork management system",
      description: "Deploy validated electronic artwork management system with revision-controlled access and mandatory print audit trails to prevent label mix-ups.",
      capaType: "Preventive",
      status: "Open",
      creationDate: "2026-05-18",
      initialPlannedDate: "2026-08-18",
      implementationLeader: "Michael Delaney",
      location: "Packaging Operations / IT",
      externalReferences: "IT-VAL-2026-0012",
    },
    {
      capaNumber: "CAPA-0003",
      deviationId: deviations[3].id,
      title: "HVAC filter PM schedule revision for Grade B cleanrooms",
      description: "Reduce filter replacement interval from 12 months to 6 months. Add HVAC filter status to environmental monitoring dashboard with automated alert thresholds.",
      capaType: "Corrective",
      status: "Closed",
      creationDate: "2026-05-30",
      initialPlannedDate: "2026-06-20",
      implementationDate: "2026-06-18",
      implementationLeader: "Ana Martinez",
      location: "Aseptic Fill / Facilities",
      externalReferences: null,
    },
    {
      capaNumber: "CAPA-0004",
      deviationId: deviations[4].id,
      title: "Implement automated calibration tracking with overdue alerts",
      description: "Integrate laboratory equipment calibration tracking with LIMS. Configure automated email alerts at 30-day and 7-day pre-expiry and on overdue.",
      capaType: "Preventive",
      status: "Open",
      creationDate: "2026-06-11",
      initialPlannedDate: "2026-07-31",
      implementationLeader: "Michael Delaney",
      location: "QC Laboratory",
      externalReferences: "LIMS-DEV-2026-0008",
    },
    {
      capaNumber: "CAPA-0005",
      deviationId: deviations[5].id,
      title: "Supplier quality agreement revision and enhanced incoming testing",
      description: "Revise SQA with excipient suppliers to include particle size distribution testing at point of manufacture. Implement skip-lot testing program for approved suppliers.",
      capaType: "Preventive",
      status: "In Progress",
      creationDate: "2026-04-22",
      initialPlannedDate: "2026-07-01",
      implementationLeader: "James Holloway",
      location: "Supply Chain / QA",
      externalReferences: "SQA-2026-0003",
    },
    {
      capaNumber: "CAPA-0006",
      deviationId: null,
      title: "Annual retraining program for batch record documentation practices",
      description: "Develop mandatory annual GMP documentation training module covering critical process parameter recording, data integrity, and batch record completion requirements.",
      capaType: "Preventive",
      status: "Open",
      creationDate: "2026-06-15",
      initialPlannedDate: "2026-09-01",
      implementationLeader: "Priya Nair",
      location: "Manufacturing / Training",
      externalReferences: null,
    },
  ]).returning();

  // Efficacy Reviews
  await db.insert(efficacyReviewsTable).values([
    {
      capaId: capas[0].id,
      status: "Pending",
      reviewer: "Dr. Sarah Chen",
      expectedDate: "2026-08-03",
      instruction: "Verify that the revised PM schedule has been implemented across all cold storage units and that monthly compressor health check records are being generated. Confirm SMS alerts are active.",
    },
    {
      capaId: capas[1].id,
      status: "Pending",
      reviewer: "Michael Delaney",
      expectedDate: "2026-10-18",
      instruction: "Confirm that the electronic artwork management system is validated and live. Review audit trail logs for three completed print runs to verify controlled access and mandatory overprinting.",
    },
    {
      capaId: capas[2].id,
      status: "Effective",
      reviewer: "James Holloway",
      expectedDate: "2026-07-18",
      reviewDate: "2026-07-15",
      instruction: "Review HVAC filter replacement records and environmental monitoring dashboard alerts for the 6-week post-implementation period. Confirm no Grade B excursions attributable to filter condition.",
      review: "Filter PM schedule revised from 12 to 6 months and deployed across all Grade B suites. Environmental monitoring dashboard now includes automated HVAC filter status with alert thresholds configured at 80% filter load. No Grade B EM excursions recorded in the 6-week post-implementation window. CAPA assessed as effective.",
    },
    {
      capaId: capas[3].id,
      status: "Pending",
      reviewer: "Ana Martinez",
      expectedDate: "2026-09-30",
      instruction: "Confirm LIMS calibration tracking module is live and that automated alerts at 30-day and 7-day pre-expiry are being generated. Review alert logs and confirm no overdue instruments.",
    },
    {
      capaId: capas[4].id,
      status: "Not Effective",
      reviewer: "Dr. Sarah Chen",
      expectedDate: "2026-08-01",
      reviewDate: "2026-07-28",
      instruction: "Review revised SQA with excipient suppliers and confirm skip-lot testing criteria are documented. Verify incoming test results for at least two lots received under the new programme.",
      review: "Revised SQA signed by three of five key excipient suppliers. Skip-lot protocol drafted but not yet fully implemented — two suppliers have not returned signed agreements. Incoming testing enhanced for one active ingredient but particle size distribution testing not yet in place for excipients. Assessed as not yet effective; CAPA owner to expedite outstanding supplier agreements and implement excipient testing by 2026-09-30.",
    },
    {
      capaId: capas[5].id,
      status: "Pending",
      reviewer: "Priya Nair",
      expectedDate: "2026-10-15",
      instruction: "Confirm annual GMP documentation training module has been deployed to LMS and that completion rates for Manufacturing and QC personnel meet the 100% target. Review post-training assessment scores.",
    },
  ]);

  // Change Controls
  await db.insert(changeControlTable).values([
    {
      changeControlNumber: "CC-0001",
      title: "Change in granulation endpoint methodology — NIR in-process testing",
      changeType: "Process",
      status: "Expert Review",
      plannedImplementationDate: "2026-08-01",
      currentSituation: "Granulation endpoint is currently determined by Loss on Drying (LOD) measurements at fixed time intervals, requiring sampling and offline analysis.",
      proposedSituation: "Replace LOD-based endpoint with real-time NIR in-process monitoring, enabling continuous endpoint determination without batch interruption.",
      location: "Solid Dosage Manufacturing — Building 3",
      hierarchicResponsible: "Dr. Sarah Chen",
      siteCoordinator: "James Holloway",
      justification: "NIR methodology reduces cycle time by approximately 40 minutes per batch and eliminates sampling bias. Expected to improve batch-to-batch consistency.",
      externalReference: "PH-TECH-2026-NIR-001",
      hrComment: "No headcount impact. One NIR specialist hired in Q1 2026. Technical training complete for 8 operators.",
      scComment: "Site committee endorses NIR implementation. Capital expenditure approved. Validation protocol (PV-2026-0034) approved.",
    },
    {
      changeControlNumber: "CC-0002",
      title: "HPLC column specification change for API purity assay",
      changeType: "Analytical",
      status: "Approved",
      plannedImplementationDate: "2026-07-01",
      currentSituation: "API purity assay uses Phenomenex Luna C18 (250×4.6mm, 5µm) column per validated method QC-METH-0047 Rev 5.",
      proposedSituation: "Replace with Waters XBridge C18 (150×4.6mm, 3.5µm) to reduce analysis time from 35 to 18 minutes while maintaining equivalent selectivity.",
      location: "QC Laboratory",
      hierarchicResponsible: "Michael Delaney",
      siteCoordinator: "Ana Martinez",
      justification: "Column shortage risk due to supplier discontinuation. Waters XBridge provides equivalent performance with faster run time and improved throughput.",
      externalReference: "QC-METH-CHANGE-2026-004",
      hrComment: "No staffing changes required. QC staff trained on new column qualification procedures.",
      scComment: "Approved. Method validation data reviewed and accepted. Regulatory filing classification: Type IB change.",
    },
    {
      changeControlNumber: "CC-0003",
      title: "Introduction of automated visual inspection system for vials",
      changeType: "Equipment",
      status: "SC Review",
      plannedImplementationDate: "2026-10-15",
      currentSituation: "Visual inspection of injectable vials is performed manually by trained inspectors at a rate of ~600 vials/hour per inspector.",
      proposedSituation: "Deploy Cognex ViDi automated visual inspection system capable of inspecting 3,600 vials/hour with documented detection sensitivity exceeding human inspection.",
      location: "Aseptic Fill — Inspection Line 2",
      hierarchicResponsible: "Dr. Sarah Chen",
      siteCoordinator: "Thomas Birch",
      justification: "Automated inspection eliminates human fatigue variability, provides 100% inspection with full audit trail, and increases throughput 6-fold to meet growing demand.",
      externalReference: "CAPEX-2026-0018",
      hrComment: null,
      scComment: null,
    },
    {
      changeControlNumber: "CC-0004",
      title: "Extended shelf life claim for Omeprazole 20mg capsules",
      changeType: "Regulatory",
      status: "HR Review",
      plannedImplementationDate: "2026-12-01",
      currentSituation: "Omeprazole 20mg capsules (Product Code: OM-20-CAP) currently have a 24-month shelf life at 25°C/60%RH.",
      proposedSituation: "Extend shelf life from 24 months to 36 months based on completed 36-month real-time stability data from three production batches.",
      location: "QA / Regulatory Affairs",
      hierarchicResponsible: "James Holloway",
      siteCoordinator: "Priya Nair",
      justification: "36-month stability data from three commercial batches all within specification. Extension reduces product wastage at pharmacy level and aligns with competitor labeling.",
      externalReference: "RA-FILING-2026-0007",
      hrComment: null,
      scComment: null,
    },
    {
      changeControlNumber: "CC-0005",
      title: "Secondary packaging line upgrade — automated cartonning system",
      changeType: "Equipment",
      status: "Draft",
      plannedImplementationDate: "2026-11-01",
      currentSituation: "Secondary packaging uses semi-automated cartonning with manual leaflet insertion and manual batch number overprinting.",
      proposedSituation: "Install fully automated IMA cartonning line with integrated leaflet insertion, vision system for batch/expiry verification, and reject station.",
      location: "Secondary Packaging — Building 5",
      hierarchicResponsible: "Michael Delaney",
      siteCoordinator: "Thomas Birch",
      justification: "Current line operating at 95% capacity. New line increases throughput by 120% and reduces labeling errors through automated vision verification.",
      externalReference: "CAPEX-2026-0024",
      hrComment: null,
      scComment: null,
    },
    {
      changeControlNumber: "CC-0006",
      title: "Site transfer of Atorvastatin 40mg tablet manufacturing",
      changeType: "Process",
      status: "Closed",
      plannedImplementationDate: "2026-05-01",
      currentSituation: "Atorvastatin 40mg tablet manufacturing is performed at Site A (legacy facility). Commercial supply has been ongoing since 2019.",
      proposedSituation: "Transfer manufacturing to Site B following successful process validation (3 PPQ batches) and regulatory approval. Site A to be decommissioned Q4 2026.",
      location: "Manufacturing — Site B",
      hierarchicResponsible: "Dr. Sarah Chen",
      siteCoordinator: "James Holloway",
      justification: "Site B has newer equipment, better capacity, and is the designated long-term manufacturing site for this product family per 2025 network rationalization strategy.",
      externalReference: "SITE-TRANSFER-AT40-2026",
      hrComment: "HR review complete. 12 operators transferred from Site A. Training and qualification complete.",
      scComment: "SC approved. All three PPQ batches passed. Regulatory submission filed and approved in target markets.",
    },
  ]);

  console.log("Seed complete.");
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
