import { pgTable, text, serial, timestamp, date, boolean } from "drizzle-orm/pg-core";
  import { createInsertSchema } from "drizzle-zod";
  import { z } from "zod/v4";

  export const deviationsTable = pgTable("deviations", {
    id: serial("id").primaryKey(),
    deviationNumber: text("deviation_number").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    immediateAction: text("immediate_action"),
    deviationType: text("deviation_type").notNull(),
    location: text("location"),
    externalReference: text("external_reference"),
    operation: text("operation"),
    equipment: text("equipment"),
    products: text("products"),
    batchLotNumber: text("batch_lot_number"),
    status: text("status").notNull().default("Open"),
    eventDate: date("event_date", { mode: "string" }).notNull(),
    detectionDate: date("detection_date", { mode: "string" }).notNull(),
    dueDate: date("due_date", { mode: "string" }).notNull(),
    extendedDate: date("extended_date", { mode: "string" }),
    areaResponsible: text("area_responsible").notNull(),
    qaExpert: text("qa_expert").notNull(),
    eventPriority: text("event_priority"),
    areaResponsibleComment: text("area_responsible_comment"),
    investigationLeader: text("investigation_leader"),
    assignedExpert: text("assigned_expert"),
    riskManager: text("risk_manager"),
    assignedAdditionalQa: text("assigned_additional_qa"),
    investigation: text("investigation"),
    productImpact: text("product_impact"),
    gxpCompliance: text("gxp_compliance"),
    gmpComment: text("gmp_comment"),
    extendedDateComment: text("extended_date_comment"),
    barrier: text("barrier"),
    secondBarrier: text("second_barrier"),
    teamMembers: text("team_members"),
    rmPotentialRisk: boolean("rm_potential_risk"),
    rmComment: text("rm_comment"),
    rootCause: text("root_cause"),
    rootCauseCategory: text("root_cause_category"),
    solvingMethod: text("solving_method"),
    isRepeatedDeviation: boolean("is_repeated_deviation"),
    repeatedDeviationComment: text("repeated_deviation_comment"),
    capaNeeded: boolean("capa_needed"),
    capaComment: text("capa_comment"),
    erNeeded: boolean("er_needed"),
    erComment: text("er_comment"),
    requiresInvestigation: boolean("requires_investigation"),
    qaComment: text("qa_comment"),
    completionComment: text("completion_comment"),
    workflowStatus: text("workflow_status"),
    areaRejectReason: text("area_reject_reason"),
    qaRejectReason: text("qa_reject_reason"),
    classification: text("classification"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  });

  export const insertDeviationSchema = createInsertSchema(deviationsTable).omit({ id: true, createdAt: true, updatedAt: true });
  export type InsertDeviation = z.infer<typeof insertDeviationSchema>;
  export type Deviation = typeof deviationsTable.$inferSelect;
